[DatePicker] Migrate docs
mui-org/core-plus-pickers pull request #12
Opened 2020-08-26 07:13 UTC by dmtrKovalenko

- [x] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui-org/material-ui/blob/next/CONTRIBUTING.md#sending-a-pull-request).

2020-08-26 07:19 UTC, dmtrKovalenko commented on docs/src/pages/components/date-picker/LocalizedDatePicker.js
> +              key={localeItem}
```suggestion
              key={localeItem}
              variant={locale === localeItem ? 'contained' : 'outlined'}
```

2020-08-26 07:20 UTC, dmtrKovalenko commented on docs/src/pages/components/date-picker/CustomInput.tsx
> +      label="Advanced keyboard"
```suggestion
      label="Custom input"
```

2020-08-26 07:21 UTC, dmtrKovalenko commented on docs/src/pages/components/date-picker/ServerRequest.tsx
> +    fetch(`/fakeApi/randomDate?month=${date.toString()}`, {
Figure out what to do with this example. I`d like to leave it and do not override with fake server function because it is required to point users that requests must be aborted in this case

2020-08-26 15:14 UTC, oliviertassinari commented on docs/src/pages/components/date-picker/date-picker.md
> +[Date pickers](https://material.io/components/pickers/) let users select a date, or a range of dates. They should be suitable for the context in which they appear.
It's a topology

```suggestion
[Date pickers](https://material.io/components/pickers/) let users select a date, or a range of dates.
```

2020-08-26 15:14 UTC, oliviertassinari commented on docs/src/pages/components/date-picker/date-picker.md
> +It is also allowed to combine `year`, `month` and `date` selection views. Views will appear in the order they passed to the `views` array.
Serial comma

```suggestion
It is also allowed to combine `year`, `month`, and `date` selection views. Views will appear in the order they passed to the `views` array.
```

2020-08-26 15:14 UTC, oliviertassinari commented on docs/src/pages/components/date-picker/date-picker.md
> +It is possible to render any picker without modal/popover and text field. This can be really helpful to build custom popover/modal containers.
filler word

```suggestion
It is possible to render any picker without modal/popover and text field. This can be helpful to build custom popover/modal containers.
```

2020-08-26 15:14 UTC, oliviertassinari commented on docs/src/pages/components/date-picker/date-picker.md
> +When date picker is used in landscape orientation it is too hard to use it, especially on mobile. That's why it will automatically change the layout by subscription to the `window.orientation` change
```suggestion
When date picker is used in landscape orientation it is too hard to use it, especially on mobile. That's why it will automatically change the layout by subscription to the `window.orientation` change. You can force a specific layout using `orientation` prop.
```

2020-08-26 15:14 UTC, oliviertassinari commented on docs/src/pages/components/date-picker/date-picker.md
> +The displaying of dates is heavily cusomizable. Use `renderDay` function to customize view of the day.
```suggestion
The displayed days are customizable with the `renderDay` function prop.
```

2020-08-26 15:14 UTC, oliviertassinari commented on docs/src/pages/components/date-picker/date-picker.md
> +and displaying server side data using `onMonthChange`, `loading` and `renderDay` props.
```suggestion
and displaying server-side data using `onMonthChange`, `loading`, and `renderDay` props.
```

2020-08-26 15:14 UTC, oliviertassinari commented on docs/pages/_app.js
> +            <LocalizationProvider dateAdapter={DateFnsAdapter}>
What's the copy & paste story? Do you want to continue the discussion on https://github.com/mui-org/material-ui-pickers/issues/1650#issuecomment-612849091?

2020-08-26 15:18 UTC, oliviertassinari commented
> There are quite a lot of issues with moved examples. I`d like to set up a proper deployment preview – it would be easier to point to the issues.

Are you referring to https://deploy-preview-12--core-plus-pickers.netlify.app/components/date-picker/?

2020-08-26 15:22 UTC, oliviertassinari commented on docs/src/pages/components/date-picker/ResponsiveDatePickers.tsx
> +        renderInput={(props) => <TextField {...props} margin="normal" />}
The demos should be singled focused

```suggestion
        label="For mobile"
        value={value}
        onChange={(newValue) => setValue(newValue)}
        renderInput={(props) => <TextField {...props} margin="normal" />}
```

Also, ideally we would have the value uncontrolled:

```suggestion
        label="For mobile"
        renderInput={(props) => <TextField {...props} margin="normal" />}
```

2020-08-26 15:25 UTC, oliviertassinari commented on docs/src/pages/components/date-picker/date-picker.md
> +{{"demo": "pages/components/date-picker/StaticDatePicker.js"}}
For a better-looking demo?

```suggestion
{{"demo": "pages/components/date-picker/StaticDatePicker.js", "bg": true}}
```

<img width="527" alt="Capture d’écran 2020-08-26 à 17 24 55" src="https://user-images.githubusercontent.com/3165635/91323388-1d082980-e7c1-11ea-9ae5-6af78fc2d592.png">

But we should likely remove the Paper component or background color from the static version

2020-08-26 15:28 UTC, oliviertassinari commented on docs/src/pages/components/date-picker/date-picker.md
> +{{"demo": "pages/components/date-picker/StaticDatePickerLandscape.js"}}
```suggestion
{{"demo": "pages/components/date-picker/StaticDatePickerLandscape.js", "bg": true}}
```

2020-08-26 15:54 UTC, dmtrKovalenko commented on docs/src/pages/components/progress/DelayingAppearance.tsx
> +  const timerRef = React.useRef<NodeJS.Timeout>();
The problem here is with the required `node` typing for the codebase. Node overrides the typing for global `setTimeout` and it returns this specific type. 

I didn't change it to `window.setTimeout` because it could be potentially run on the server-side. Or maybe @eps1lon could provide a better solution

2020-08-26 15:55 UTC, dmtrKovalenko commented on docs/src/pages/components/date-picker/LocalizedDatePicker.tsx
> +import { DatePicker } from '@material-ui/lab/DatePicker';
The file exports 3 pickers `DatePicker`, `MobileDatePicker` & `ResponsiveDatePicker`

2020-08-26 16:00 UTC, oliviertassinari commented on docs/src/pages/components/date-picker/LocalizedDatePicker.tsx
> +import { DatePicker } from '@material-ui/lab/DatePicker';
On a different note: should we break the file into 3 files? To increase isolation and tree-shaking potential?

2020-08-26 16:01 UTC, dmtrKovalenko commented on docs/pages/_app.js
> +            <LocalizationProvider dateAdapter={DateFnsAdapter}>
Yeah, potentially we could wrap each example in the localization provider, but I suppose it would be even weird for most of the users: because they already wrapped the root with this `LocalizationProvider`. 

One most important question: 
Where should we mention the requirement of the context provider? On pickers docs, we have our own "entry point" (getting started page), but here potentially any user can just import the component. And here wrapping demo with the provider could be helpful.  

> I don't know the answer :)

2020-08-26 16:02 UTC, dmtrKovalenko commented on docs/src/pages/components/date-picker/date-picker.md
> +{{"demo": "pages/components/date-picker/StaticDatePicker.js"}}
Cool! So no need in the additional Paper wrapper

2020-08-26 16:04 UTC, oliviertassinari commented on docs/pages/_app.js
> +            <LocalizationProvider dateAdapter={DateFnsAdapter}>
cc @mbrookes Any thoughts on what the best approach would be for a required context?

2020-08-26 16:10 UTC, oliviertassinari commented on docs/src/pages/components/progress/DelayingAppearance.tsx
> +  const timerRef = React.useRef<NodeJS.Timeout>();
Mayby any? We should never need to manipulate the value.

2020-08-26 16:35 UTC, dmtrKovalenko commented on docs/src/pages/components/date-picker/LocalizedDatePicker.tsx
> +import { DatePicker } from '@material-ui/lab/DatePicker';
Yes, we need to break them, but probably they should be hosted inside the DatePicker folder? Because it is like 5 loc per file?

2020-08-26 16:39 UTC, dmtrKovalenko commented on docs/src/pages/components/date-picker/LocalizedDatePicker.tsx
> +    <div style={{ width: 300 }}>
In order to display button group under the text field. Without width : 
![image](https://user-images.githubusercontent.com/16926049/91331753-db34ae80-e7d3-11ea-815c-62973862f114.png)

2020-08-26 19:09 UTC, eps1lon commented on docs/src/pages/components/progress/DelayingAppearance.tsx
> +  const timerRef = React.useRef<NodeJS.Timeout>();
Does `ReturnType<typeof setTimeout>` work? That should be closer to what you're actually doing and works in any environment implementing `setTimeout`.

If TypeScript had flow analysis for React it would realize that we only ever assign to it in the browser unless `setTimeout` is called during render.

2020-08-26 19:57 UTC, mbrookes requested changes

2020-08-26 19:57 UTC, mbrookes commented on docs/src/pages/components/date-picker/date-picker.md
> +<p class="description">Date pickers let users select a date.</p>
```suggestion
<p class="description">Date pickers let the user select a date.</p>
```

2020-08-26 19:57 UTC, mbrookes commented on docs/src/pages/components/date-picker/date-picker.md
> +[Date pickers](https://material.io/components/pickers/) let users select a date. Date pickers are displayed with:
```suggestion
[Date pickers](https://material.io/components/pickers/) let the user select a date. Date pickers are displayed with:
```

2020-08-26 19:57 UTC, mbrookes commented on docs/src/pages/components/date-picker/date-picker.md
> +This can be customized by `desktopModeMediaQuery` prop.
```suggestion
This can be customized with the `desktopModeMediaQuery` prop.
```

2020-08-26 19:57 UTC, mbrookes commented on docs/src/pages/components/date-picker/date-picker.md
> +Use `LocalizationProvider` to change the date-engine locale that is using to render date picker. Here is an example of changing locale for `date-fns` adapter:
```suggestion
Use `LocalizationProvider` to change the date-engine locale that is used to render the date picker. Here is an example of changing the locale for the `date-fns` adapter:
```

2020-08-26 19:57 UTC, mbrookes commented on docs/src/pages/components/date-picker/date-picker.md
> +It is also allowed to combine `year`, `month`, and `date` selection views. Views will appear in the order they passed to the `views` array.
```suggestion
It is possible to combine `year`, `month`, and `date` selection views. Views will appear in the order they passed to the `views` array.
```

2020-08-26 19:57 UTC, mbrookes commented on docs/src/pages/components/date-picker/date-picker.md
> +It is possible to render any picker without modal/popover and text field. This can be helpful to build custom popover/modal containers.
```suggestion
It is possible to render any picker without the modal/popover and text field. This can be helpful to build custom popover/modal containers.
```

2020-08-26 19:57 UTC, mbrookes commented on docs/src/pages/components/date-picker/date-picker.md
> +When date picker is used in landscape orientation it is too hard to use it, especially on mobile. That's why it will automatically change the layout by subscription to the `window.orientation` change
```suggestion
For ease of use the date picker will automatically change the layout between portrait and landscape by subscription to the `window.orientation` change. You can force a specific layout using `orientation` prop.
```

2020-08-26 19:57 UTC, mbrookes commented on docs/src/pages/components/date-picker/date-picker.md
> +You can customize rendering input by `renderInput` prop. But make sure you will spread `ref` and `inputProps` correctly to the custom input component.
```suggestion
You can customize rendering of the input with the `renderInput` prop. Make sure to spread `ref` and `inputProps` correctly to the custom input component.
```

2020-08-26 19:57 UTC, mbrookes commented on docs/src/pages/components/date-picker/date-picker.md
> +## Customize day rendering
```suggestion
## Customized day rendering
```

2020-08-26 19:57 UTC, mbrookes commented on docs/src/pages/components/date-picker/date-picker.md
> +You can leverage our internal [Day](/api/Day) component, and render it in default way by spreading `dayProps` argument.
```suggestion
You can take advantage of the internal [Day](/api/Day) component, and render it in default way by spreading `dayProps` argument.
```
"in default way" - not sure what this means?

2020-08-26 19:57 UTC, mbrookes commented on docs/src/pages/components/date-picker/date-picker.md
> +Sometimes it's required to display additional info right in the calendar. Here is an example of prefetching
```suggestion
Sometimes it may be necessary to display additional info right in the calendar. Here is an example of prefetching
```

2020-08-26 19:57 UTC, mbrookes commented on docs/src/pages/components/date-picker/date-picker.md
> +and displaying server-side data using `onMonthChange`, `loading`, and `renderDay` props.
```suggestion
and displaying server-side data using the `onMonthChange`, `loading`, and `renderDay` props.
```

2020-08-27 08:10 UTC, dmtrKovalenko commented on docs/src/pages/components/date-picker/date-picker.md
> +You can leverage our internal [Day](/api/Day) component, and render it in default way by spreading `dayProps` argument.
Yeah I think it is out of date sentence 
```suggestion
You can take advantage of the internal [PickersDay](/api/PickersDay) component. 
```

2020-08-27 08:23 UTC, oliviertassinari commented on docs/src/pages/components/date-picker/date-picker.md
> +You can take advantage of the internal [PickersDay](/api/PickersDay) component.
Two issues. Urls need a leading slash, Urls are in snack-case.

`/api/pickers-day/`

2020-08-27 09:02 UTC, dmtrKovalenko commented on docs/src/pages/components/date-picker/ServerRequest.tsx
> +    fetch(`/fakeApi/randomDate?month=${date.toString()}`, {
Canceling request is required in this case because we should not allow previous request to update the state if the user already clicks to switch a month again. 


![Screen Recording 2020-08-27 at 11 49 07](https://user-images.githubusercontent.com/16926049/91420290-27780100-e85d-11ea-9131-7af1f1e1f99d.gif)

2020-08-27 10:00 UTC, oliviertassinari commented on docs/src/pages/components/date-picker/LocalizedDatePicker.tsx
> +import { DatePicker } from '@material-ui/lab/DatePicker';
Splitting it in 3 files would help with:

- Predictible import paths (reduce the need to check the documentation). 
- Help generate dedicated API pages for each variant we expose.

But we also need to consider the cons. For instance:

- If we expose the same API, 3 docs pages could be more confusing, in which case we might disable the generation and only gain predictable import paths.
- If we don't keep support for 1 level import path in v5, the predictable import paths argument won't hold.

2020-08-27 21:11 UTC, mbrookes commented on docs/src/pages/components/date-picker/date-picker.md
> +Will be rendered to modal dialog on mobile and textfield with popover on desktop.
```suggestion
The date picker will be rendered to modal dialog on mobile and textfield with popover on desktop.
```

2020-08-27 21:11 UTC, mbrookes commented on docs/src/pages/components/date-picker/date-picker.md
> +For ease of use the date picker will automatically change the layout between portrait and landscape by subscription to the `window.orientation` change. You can force a specific layout using `orientat
```suggestion
For ease of use the date picker will automatically change the layout between portrait and landscape by subscription to the `window.orientation` change. You can force a specific layout using the `orientation` prop.
```

2020-08-27 22:11 UTC, mbrookes requested changes

2020-08-27 22:11 UTC, mbrookes commented on docs/src/pages/components/time-picker/time-picker.md
> +<p class="description">Time pickers let user select a single time.</p>
```suggestion
<p class="description">Time pickers allow the user to select a single time.</p>
```

2020-08-27 22:11 UTC, mbrookes commented on docs/src/pages/components/time-picker/time-picker.md
> +Time pickers let users select a single time (in the hours:minutes format).
```suggestion
Time pickers allow the user to select a single time (in the hours:minutes format).
```

2020-08-27 22:11 UTC, mbrookes commented on docs/src/pages/components/time-picker/time-picker.md
> +A time picker will automatically adjust to the locale's time setting, i.e. the 12-hour or 24-hour format. This can be controlled with `ampm` prop.
```suggestion
The time picker will automatically adjust to the locale's time setting, i.e. the 12-hour or 24-hour format. This can be controlled with `ampm` prop.
```

2020-08-27 22:11 UTC, mbrookes commented on docs/src/pages/components/time-picker/time-picker.md
> +Use `LocalizationProvider` to change the date-engine locale that is using to render time picker. Note that `am/pm` setting is switching automatically:
```suggestion
Use `LocalizationProvider` to change the date-engine locale that is used to render the time picker. Note that `am/pm` setting is switched automatically:
```

2020-08-27 22:11 UTC, mbrookes commented on docs/src/pages/components/time-picker/time-picker.md
> +This can be customized by `desktopModeMediaQuery` prop.
```suggestion
This can be customized with the `desktopModeMediaQuery` prop.
```

2020-08-27 22:11 UTC, mbrookes commented on docs/src/pages/components/time-picker/time-picker.md
> +It is possible to render any picker inline. This will be really to build custom popover/modal containers.
```suggestion
It is possible to render any picker inline. This will enable building custom popover/modal containers.
```

2020-08-27 22:11 UTC, mbrookes commented on docs/src/pages/components/time-picker/time-picker.md
> +Seconds input can be used for selection of a precise time point.
```suggestion
The seconds input can be used for selection of a precise time point.
```

2020-08-28 08:46 UTC, oliviertassinari approved these changes

2020-08-28 10:45 UTC, merged