[DateTimePicker] Migrate demos
mui-org/core-plus-pickers pull request #14
Opened 2020-08-26 17:52 UTC by dmtrKovalenko

- [x] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui-org/material-ui/blob/next/CONTRIBUTING.md#sending-a-pull-request).

2020-08-26 20:08 UTC, mbrookes requested changes

2020-08-26 20:08 UTC, mbrookes commented on docs/src/pages/components/date-time-picker/date-time-picker.md
> +This component combines date & time pickers. It allows to select both date and time with the same control.
```suggestion
This component combines the date & time pickers. It allows to select both date and time with the same control.
```

2020-08-26 20:08 UTC, mbrookes commented on docs/src/pages/components/date-time-picker/date-time-picker.md
> +Make sure that this component is actually combined [DatePicker](/components/date-picker) and [TimePicker](/components/time-picker) so any prop of these components could be passed to the DateTimePicke
```suggestion
Note that this component is the [DatePicker](/components/date-picker) and [TimePicker](/components/time-picker) 
 component combined, so any of these components' props can be passed to the DateTimePicker.
```

2020-08-26 20:08 UTC, mbrookes commented on docs/src/pages/components/date-time-picker/date-time-picker.md
> +The date time picker component is designed and optimized for the device it runs on.
"date time picker" or "`DateTimePicker`"?

2020-08-26 20:08 UTC, mbrookes commented on docs/src/pages/components/date-time-picker/date-time-picker.md
> +This can be customized by `desktopModeMediaQuery` prop.
```suggestion
This can be customized with the `desktopModeMediaQuery` prop.
```

2020-08-26 20:08 UTC, mbrookes commented on docs/src/pages/components/date-time-picker/date-time-picker.md
> +- using `minDateTime`/`maxDateTime`, its possible to restrict time selection before or after a particular moment in time
```suggestion
- by using `minDateTime`/`maxDateTime` its possible to restrict time selection to before or after a particular moment in time
```

2020-08-26 20:08 UTC, mbrookes commented on docs/src/pages/components/date-time-picker/date-time-picker.md
> +Here are some examples of heavily customized date & time pickers
```suggestion
Here are some examples of heavily customized date & time pickers:
```

2020-08-26 22:55 UTC, oliviertassinari commented on docs/src/pages/components/date-time-picker/BasicDateTimePicker.js
> +      renderInput={(props) => <TextField variant="outlined" {...props} />}
```suggestion
      renderInput={(props) => <TextField {...props} />}
```

2020-08-26 22:55 UTC, oliviertassinari commented on docs/src/pages/components/date-time-picker/DateTimeValidation.tsx
>  export default function DateTimePickerValidation() {
```suggestion
export default function DateTimeValidation() {
```

2020-08-26 22:55 UTC, oliviertassinari commented on docs/src/pages/components/date-time-picker/ResponsiveDateTimePickers.tsx
> +export default function ResponsiveDateTimePickerDemo() {
```suggestion
export default function ResponsiveDateTimePickers() {
```

2020-08-26 22:55 UTC, oliviertassinari commented on docs/src/pages/components/date-time-picker/ResponsiveDateTimePickers.tsx
> +        ampm
No need to add more variant to the demo, let's show one feature at the time.


```suggestion
```

2020-08-26 22:55 UTC, oliviertassinari commented on docs/src/pages/components/date-time-picker/date-time-picker.md
> +<p class="description"> Combined date & time picker. </p>
```suggestion
<p class="description">Combined date & time picker.</p>
```

2020-08-26 22:55 UTC, oliviertassinari commented on docs/src/pages/components/date-time-picker/date-time-picker.md
> +{{"demo": "pages/components/date-time-picker/BasicDateTimePicker.js" }}
```suggestion
{{"demo": "pages/components/date-time-picker/BasicDateTimePicker.js"}}
```

2020-08-26 22:55 UTC, oliviertassinari commented on docs/src/pages/components/date-time-picker/date-time-picker.md
> +{{"demo": "pages/components/date-time-picker/CustomDateTimePicker.js" }}
```suggestion
{{"demo": "pages/components/date-time-picker/CustomDateTimePicker.js"}}
```

2020-08-26 22:55 UTC, oliviertassinari commented on docs/src/pages/components/date-time-picker/date-time-picker.md
> +{{"demo": "pages/components/date-time-picker/DateTimeValidation.js" }}
```suggestion
{{"demo": "pages/components/date-time-picker/DateTimeValidation.js"}}
```

2020-08-26 22:55 UTC, oliviertassinari commented on docs/src/pages/components/date-time-picker/date-time-picker.md
> +{{"demo": "pages/components/date-time-picker/ResponsiveDateTimePickers.js" }}
```suggestion
{{"demo": "pages/components/date-time-picker/ResponsiveDateTimePickers.js"}}
```

2020-08-27 08:18 UTC, dmtrKovalenko commented on docs/src/pages/components/date-time-picker/date-time-picker.md
> +The date time picker component is designed and optimized for the device it runs on.
Definitely `DateTimePicker` sounds better :) thx! 
```suggestion
The `DateTimePicker` component is designed and optimized for the device it runs on.
```

2020-08-27 14:38 UTC, oliviertassinari commented on docs/src/pages/components/date-time-picker/date-time-picker.md
> +Note that this component is the [DatePicker](/components/date-picker) and [TimePicker](/components/time-picker)
leading slash, always for our docs

```suggestion
Note that this component is the [DatePicker](/components/date-picker/) and [TimePicker](/components/time-picker/) 
```

2020-08-27 14:39 UTC, oliviertassinari approved these changes

2020-08-28 06:47 UTC, merged