DateRangePicker
mui-org/core-plus-pickers pull request #25
Opened 2020-09-03 19:57 UTC by dmtrKovalenko

- [ ] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui-org/material-ui/blob/next/CONTRIBUTING.md#sending-a-pull-request).

2020-09-03 21:49 UTC, oliviertassinari reviewed
Great!

2020-09-03 21:49 UTC, oliviertassinari commented on packages/material-ui-lab/src/StaticDateTimePicker/StaticDateTimePicker.ts
> +   * Default calendar month displayed when `value={null}`. @default `new Date()`
```suggestion
   * Default calendar month displayed when `value={null}`.
   * @default `new Date()`
```

2020-09-03 21:49 UTC, oliviertassinari commented on packages/material-ui-lab/src/StaticDateRangePicker/StaticDateRangePicker.tsx
> +   * onChange callback @DateIOType.
```suggestion
   * Callback fired when the value (the selected date) changes.
```

2020-09-03 21:49 UTC, oliviertassinari commented on packages/material-ui-lab/src/StaticDateRangePicker/StaticDateRangePicker.tsx
> +   * On close callback.
```suggestion
   * Callback fired when the popup requests to be closed.
   * Use in controlled mode (see open).
```

2020-09-03 21:49 UTC, oliviertassinari commented on packages/material-ui-lab/src/StaticDateRangePicker/StaticDateRangePicker.tsx
> +   * On open callback.
```suggestion
   * Callback fired when the popup requests to be opened.
   * Use in controlled mode (see open).
```

2020-09-03 21:49 UTC, oliviertassinari commented on packages/material-ui-lab/src/StaticDateRangePicker/StaticDateRangePicker.tsx
> +   * Controlled picker open state.
```suggestion
   * Control the popup` open state.
```

2020-09-03 21:49 UTC, oliviertassinari commented on packages/material-ui-lab/src/StaticDateRangePicker/StaticDateRangePicker.tsx
> +   * Picker value.
```suggestion
   * The value of the range picker.
```

2020-09-03 21:49 UTC, oliviertassinari commented on packages/material-ui-lab/src/StaticDateRangePicker/StaticDateRangePicker.tsx
> +   * Show toolbar even in desktop mode.
```suggestion
   * If `true`, show the toolbar even in desktop mode.
```

2020-09-03 21:49 UTC, oliviertassinari commented on packages/material-ui-lab/src/StaticDateRangePicker/StaticDateRangePicker.tsx
> +   * If `true` picker will immediately close after submitting full date.
```suggestion
   * If `true`, the popup won't close when a value is selected.
```

2020-09-03 21:49 UTC, oliviertassinari commented on packages/material-ui-lab/src/StaticDateRangePicker/StaticDateRangePicker.tsx
> +   * Disable picker and text field.
```suggestion
   * If `true`, the picker and text field are disabled.
```

2020-09-03 21:49 UTC, oliviertassinari commented on packages/material-ui-lab/src/StaticDateRangePicker/StaticDateRangePicker.tsx
> +   * if `true` after selecting `start` date  calendar will not automatically switch to the month of `end` date
```suggestion
   * If `true`, after selecting a `start` date, the calendar doesn't automatically switch to the month of the `end` date.
```

2020-09-03 21:49 UTC, oliviertassinari commented on packages/material-ui-lab/src/DateRangePicker/makeDateRangePicker.tsx
> +   * Text for end input label and toolbar placeholder
```suggestion
   * Text for end input label and toolbar placeholder.
```

2020-09-03 21:49 UTC, oliviertassinari commented on packages/material-ui-lab/src/DateRangePicker/makeDateRangePicker.tsx
> +   * Text for start input label and toolbar placeholder
```suggestion
   * Text for start input label and toolbar placeholder.
```

2020-09-03 21:49 UTC, oliviertassinari commented on packages/material-ui-lab/src/StaticDateRangePicker/StaticDateRangePicker.tsx
> +   * If `true`, will fire `onChange` on click even if same date is selected.
```suggestion
   * If `true`, `onChange` is fired on click even if the same date is selected.
```

2020-09-03 21:49 UTC, oliviertassinari commented on packages/material-ui-lab/src/StaticDateRangePicker/StaticDateRangePicker.tsx
> +   * How many calendars render on **desktop** DateRangePicker.
```suggestion
   * The number of calendars that render on **desktop**.
```

2020-09-03 21:49 UTC, oliviertassinari commented on packages/material-ui-lab/src/DayPicker/DayPicker.tsx
> +   * Default calendar month displayed when `value={null}`. @default `new Date()`
```suggestion
   * Default calendar month displayed when `value={null}`.
   * @default `new Date()`
```

2020-09-03 21:49 UTC, oliviertassinari commented on packages/material-ui-lab/src/DateTimePicker/DateTimePicker.tsx
> +   * Default calendar month displayed when `value={null}`. @default `new Date()`
```suggestion
   * Default calendar month displayed when `value={null}`.
   * @default `new Date()`
```

2020-09-03 21:50 UTC, oliviertassinari commented
While I have proposed suggestion for the generated descriptions of the prop-types, I believe we would need to update the TypeScript sources directly.

2020-09-04 04:37 UTC, dmtrKovalenko commented on docs/src/pages/components/date-range-picker/date-range-picker.md
> +<PageMeta component="DateRangePicker" />
Should I add the same for other components?

2020-09-04 04:38 UTC, dmtrKovalenko commented on docs/src/pages/components/date-range-picker/date-range-picker.md
> +Basic DateRangePicker example, make sure that you can pass almost any prop of [DatePicker]('/api/date-range-picker')
This mean actually date picker.

2020-09-04 06:58 UTC, dmtrKovalenko commented on packages/material-ui-lab/src/StaticDateRangePicker/StaticDateRangePicker.tsx
> +   * onChange callback @DateIOType.
You need to consider how documentation will show the date values because prop types infer them as any. I used this special jsdoc tag

2020-09-04 07:00 UTC, dmtrKovalenko commented on packages/material-ui-lab/src/StaticDateRangePicker/StaticDateRangePicker.tsx
> +   * Picker value.
These props are reused in typescript, so we need to give a more generalized description. I called it `The value of the picker.`

2020-09-04 10:25 UTC, oliviertassinari commented on docs/src/pages/components/date-range-picker/date-range-picker.md
> +<PageMeta component="DateRangePicker" />
We will need to but it relies on a more recent version of the documentation so we have no feedback that it's done right or wrong.

2020-09-04 13:34 UTC, oliviertassinari approved these changes

2020-09-04 17:53 UTC, mbrookes requested changes

2020-09-04 17:53 UTC, mbrookes commented on docs/src/pages/components/date-range-picker/date-range-picker.md
> +> The date range picker will be made available in the coming months for production use as part of a paid extension to the community edition (MIT license) of Material-UI.
```suggestion
> The date range picker will be made available in the coming months for production use as part of a paid extension (commercial license) to the community edition (MIT license) of Material-UI.
```
```suggestion
> The date range picker will be made available in the coming months for production use as part of a paid extension to the community edition (MIT license) of Material-UI.
```

2020-09-04 17:53 UTC, mbrookes commented on docs/src/pages/components/date-range-picker/date-range-picker.md
> +> This paid extension will include advanced components (rich data grid, date range picker, tree view drag & drop, etc.). Pricing for early access will start with an affordable plan.
```suggestion
> This paid extension will include advanced components (rich data grid, date range picker, tree view drag & drop, etc.). [Early access](https://material-ui.com/store/items/material-ui-x/) starts at an affordable price.
```

(Are we saying that the final price will be unaffordable? 😄 )

2020-09-04 17:53 UTC, mbrookes commented on docs/src/pages/components/date-range-picker/date-range-picker.md
> +The [date range pickers](https://material.io/components/pickers/) let users select a range of dates.
```suggestion
The [date range pickers](https://material.io/components/pickers/) let the user select a range of dates.
```

2020-09-04 17:53 UTC, mbrookes commented on docs/src/pages/components/date-range-picker/date-range-picker.md
> +Basic DateRangePicker example, make sure that you can pass almost any prop of [DatePicker]('/api/date-picker/')
```suggestion
Basic DateRangePicker example. Note that you can pass almost any prop from [DatePicker]('/api/date-picker/').
```

2020-09-04 17:53 UTC, mbrookes commented on docs/src/pages/components/date-range-picker/date-range-picker.md
> +The date range picker component is designed and optimized for the device it runs on.
```suggestion
The date range picker component is designed to be optimized for the device it runs on.
```

2020-09-04 17:53 UTC, mbrookes commented on docs/src/pages/components/date-range-picker/date-range-picker.md
> +This can be customized by `desktopModeMediaQuery` prop.
```suggestion
This can be customized with the `desktopModeMediaQuery` prop.
```

2020-09-04 17:53 UTC, mbrookes commented on docs/src/pages/components/date-range-picker/date-range-picker.md
> +## Different amount of calendars
```suggestion
## Different number of months
```

2020-09-04 17:53 UTC, mbrookes commented on docs/src/pages/components/date-range-picker/date-range-picker.md
> +Make sure that `calendars` prop is working only for desktop mode.
```suggestion
Note that the `calendars` prop only works in desktop mode.
```
(We probably need to rethink the name of this prop...)

2020-09-04 17:53 UTC, mbrookes commented on docs/src/pages/components/date-range-picker/date-range-picker.md
> +Disabling dates performs just like in simple `DatePicker`
```suggestion
Disabling dates behaves the same as the simple `DatePicker`.
```

2020-09-04 17:53 UTC, mbrookes commented on docs/src/pages/components/date-range-picker/date-range-picker.md
> +You can customize rendering input by `renderInput` prop. For `DateRangePicker` it takes **2** parameters – for start and end input respectively.
```suggestion
You can customize  the rendered input with the `renderInput` prop. For `DateRangePicker` it takes **2** parameters – for start and end input respectively.
```

2020-09-04 17:53 UTC, mbrookes commented on docs/src/pages/components/date-range-picker/date-range-picker.md
> +So if you need to render custom input make sure you will spread `ref` and `inputProps` correctly to the input components.
```suggestion
If you need to render custom input make sure to spread `ref` and `inputProps` correctly to the input components.
```

2020-09-04 17:53 UTC, mbrookes commented on docs/src/pages/components/date-range-picker/date-range-picker.md
> +It is possible to render any picker without modal or popper. For that use `StaticDateRangePicker`.
```suggestion
It is possible to render any picker without a modal or popper. For this use `StaticDateRangePicker`.
```

2020-09-04 17:53 UTC, mbrookes commented on docs/src/pages/components/date-range-picker/date-range-picker.md
> +> ⚠️⚠️ The date range picker is unstable, it's **not suitable** for usage in production. ⚠️⚠️
```suggestion
> ⚠️⚠️ The date range picker is unstable, and **not suitable** for usage in production. ⚠️⚠️
```

2020-09-07 16:03 UTC, merged